### PR TITLE
Merge Sprint 1 Into Main

### PR DESCRIPTION
**Pull request by zperry4**
Includes API call & various UI elements / components

### CODE REVIEW

**Review by Manan-dev — APPROVED** [review]
Good work team!!!

**Review by cgraha37 — APPROVED** [review]
Looks presentation ready!

**Comment by zperry4** [comment]
We are so awesome.

**Comment by rpatel90** [comment]
approved - good job guys :)

**Review by ttulsi01 — APPROVED** [review]
Well done!

**Pull request merged**
